apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: gitops-demo-local

resources:
- ../../base

images:
- name: ghcr.io/gauravb741/gitops-kubernetes-deployer
  newName: ghcr.io/gauravb741/gitops-kubernetes-deployer
  newTag: sha-5675243



patches:
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 2
  target:
    kind: Deployment
    name: gitops-demo
- patch: |-
    - op: replace
      path: /spec/type
      value: NodePort
    - op: add
      path: /spec/ports/0/nodePort
      value: 30080
  target:
    kind: Service
    name: gitops-demo
- patch: |-
    - op: replace
      path: /data/APP_ENV
      value: local-kubernetes
  target:
    kind: ConfigMap
    name: gitops-demo-config
